// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mcc-driver/ActiveJob.tsx": () => import("../components/mockups/mcc-driver/ActiveJob.tsx"),
  "./components/mockups/mcc-driver/JobInbox.tsx": () => import("../components/mockups/mcc-driver/JobInbox.tsx"),
  "./components/mockups/mcc-driver/OtpLogin.tsx": () => import("../components/mockups/mcc-driver/OtpLogin.tsx")
};
