-- ============================================================================
-- 20260904_provider_call_prospects.sql
-- ----------------------------------------------------------------------------
-- Provider Call List — manual B2B provider-acquisition cold-call tracking.
--
-- This is a DIFFERENT feature from the AI Outreach Engine (outreach_leads /
-- outreach-admin.js), which auto-discovers leads and drafts+sends AI email/SMS
-- at scale. This schema is for a human caller (Maria) working a pre-built list
-- of provider prospects by phone, market by market, logging call attempts,
-- outcomes, and bid-pack pricing negotiation as she goes. No email addresses
-- are involved — every prospect here was sourced from Google Places and is
-- contacted by phone only.
--
-- Source: Jordan-provided National Call List (Google Places, retrieved
-- 20 Aug 2026) covering 8 markets (#1, #2, #3, #4, #5, #7, #8, #9 of the
-- ranked MCC top-10 — #6 Atlanta and #10 Central/North NJ already ran under a
-- separate, earlier workbook and are not part of this import).
--
-- Apply manually via the Supabase SQL Editor (this codebase does not run
-- migrations automatically), same as every other migration in this repo.
-- Idempotent: CREATE TABLE IF NOT EXISTS + ON CONFLICT DO NOTHING seeds, so
-- re-running is safe.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- provider_call_markets — one row per target market, carrying the call-prep
-- narrative (beachhead arc, regulatory hook, how to play it) so the admin
-- panel can show a caller the context for the market they're about to work,
-- not just a bare list of names and numbers.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS provider_call_markets (
    market              text PRIMARY KEY,
    market_rank         integer NOT NULL,
    title               text,
    beachhead_arc       text,
    regulatory_context  text,
    how_to_play_it      text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- provider_call_bid_packs — static reference pricing tiers for the B1/B2/B3
-- pricing-negotiation questions on each call (Starter/Standard/Pro/Shop, plus
-- the "Floor" standing rule). Small and rarely changes, but keeping it in the
-- DB (rather than hardcoded in the function) means the admin panel can render
-- it and Jordan can adjust pricing without a code deploy.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS provider_call_bid_packs (
    pack_name                          text PRIMARY KEY,
    sort_order                         integer NOT NULL,
    bids                               integer,
    price                              numeric,
    cost_per_bid                       numeric,
    implied_cost_per_won_customer      numeric,
    notes                              text
);

INSERT INTO provider_call_bid_packs (pack_name, sort_order, bids, price, cost_per_bid, implied_cost_per_won_customer, notes) VALUES
    ('Starter',  1, 10,  100, 10, 30, NULL),
    ('Standard', 2, 25,  225, 9,  27, NULL),
    ('Pro',      3, 50,  400, 8,  24, NULL),
    ('Shop',     4, 100, 700, 7,  21, NULL),
    ('Floor (standing rule)', 5, NULL, NULL, 3, 9, 'Standing floor — do not quote a per-bid cost below this without checking with Jordan first.')
ON CONFLICT (pack_name) DO NOTHING;

-- ----------------------------------------------------------------------------
-- provider_call_prospects — one row per business on the call list. Reference
-- columns (business_name through why_this_one) are seeded from Google Places
-- and should not be edited by callers. The "blue-shaded" columns from the
-- original spreadsheet — contact_name, attempt_1/2/3, outcome, the B1/B2/B3/R3
-- pricing-and-fit fields, bid_pack_pitched, what_they_said, c2_first_refusal,
-- notes — are what a caller fills in while/after working a prospect.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS provider_call_prospects (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    market              text NOT NULL REFERENCES provider_call_markets(market) ON DELETE CASCADE,
    row_number          integer NOT NULL,

    -- Reference data — sourced from Google Places, leave alone so rollups stay meaningful.
    business_name       text NOT NULL,
    segment             text,
    priority            integer CHECK (priority IN (1, 2, 3)),
    city                text,
    county              text,
    address             text,
    phone               text,
    google_rating       numeric,
    review_count        integer,
    screening_flags     text,
    why_this_one        text,

    -- Caller-entered fields.
    contact_name        text,
    attempt_1           text,
    attempt_2           text,
    attempt_3           text,
    outcome             text NOT NULL DEFAULT 'Not attempted',
    b1_send_bid         text,   -- "B1 Send a bid at $10?" — Yes / No / etc.
    b2_fair_price       numeric,
    b2_price_unit       text,   -- "Per BID sent" or "Per customer won" — only the former counts toward avg fair price
    b3_bid_style        text,
    r3_yes_reason       text,   -- "What makes it a YES"
    r3_no_reason        text,   -- "What makes it a NO"
    bid_pack_pitched    text,
    what_they_said      text,
    c2_first_refusal    text,
    notes                text,
    caller              text NOT NULL DEFAULT 'Maria',

    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),

    UNIQUE (market, row_number)
);

CREATE INDEX IF NOT EXISTS idx_provider_call_prospects_market   ON provider_call_prospects(market);
CREATE INDEX IF NOT EXISTS idx_provider_call_prospects_priority ON provider_call_prospects(priority);
CREATE INDEX IF NOT EXISTS idx_provider_call_prospects_outcome  ON provider_call_prospects(outcome);

-- updated_at auto-touch on edit, same pattern used elsewhere in this repo.
CREATE OR REPLACE FUNCTION provider_call_prospects_touch_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_provider_call_prospects_touch ON provider_call_prospects;
CREATE TRIGGER trg_provider_call_prospects_touch
  BEFORE UPDATE ON provider_call_prospects
  FOR EACH ROW EXECUTE FUNCTION provider_call_prospects_touch_updated_at();

-- ----------------------------------------------------------------------------
-- RLS — enabled with zero policies, service-role-only by design. Same pattern
-- as admin_team_members / admin_team_invites / chat_conversations: every read
-- and write goes through a Netlify function using the service-role key, never
-- directly from the browser.
-- ----------------------------------------------------------------------------
ALTER TABLE provider_call_markets    ENABLE ROW LEVEL SECURITY;
ALTER TABLE provider_call_bid_packs  ENABLE ROW LEVEL SECURITY;
ALTER TABLE provider_call_prospects  ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- Seed data — 8 markets + 130 prospects, extracted from Jordan's
-- MCC_National_Call_List.xlsx (Google Places, retrieved 20 Aug 2026).
-- Caller: Maria. Every row starts at Outcome = 'Not attempted' — no calls
-- have been made yet against this list.
-- ============================================================================

-- Seed: 8 markets (National Provider Call List, retrieved from Google Places 20 Aug 2026)
INSERT INTO provider_call_markets (market, market_rank, title, beachhead_arc, regulatory_context, how_to_play_it) VALUES
('Phoenix-Scottsdale, AZ', 1, 'MCC — Phoenix–Scottsdale, AZ  ·  Market #1', 'Scottsdale / Tempe / Chandler / Gilbert  ·  Maricopa County (ADEQ Area A)', 'Maricopa sits inside ADEQ''s Area A mandatory emissions zone — gasoline vehicles more than five years old must pass before registration renews. Most test every two years at $17; diesels test annually. Arizona has no safety inspection, so emissions is the only regulatory touchpoint, and year-round dry weather means mobile techs can work outdoors 12 months a year.', 'Lead with weather and volume, not the calendar — the biennial cycle is weaker than Atlanta''s annual one. The real pitch here is that a mobile tech in Phoenix never loses a working day to weather, so bid volume is the constraint, not capacity.'),
('Dallas-Fort Worth, TX', 2, 'MCC — Dallas–Fort Worth, TX  ·  Market #2', 'Plano / Frisco / Richardson / North Dallas  ·  Collin, Dallas, Denton, Tarrant Counties', 'Texas eliminated the annual safety inspection for non-commercial vehicles on 1 Jan 2025, replacing it with a $7.50 registration fee. Annual emissions testing still applies across the DFW counties. Shops kept the emissions test but lost the safety inspection — the cheap walk-in that used to put a car on the lift and surface paid repair work.', 'This is the strongest listening question on the whole list: ask what the loss of the safety inspection did to their walk-in traffic. Shops that felt it will self-describe a lead-generation problem before Maria ever has to name one.'),
('Houston, TX', 3, 'MCC — Houston, TX  ·  Market #3', 'Cypress / Katy / Tomball / NW Houston  ·  Harris, Montgomery, Fort Bend Counties', 'Same regulatory picture as DFW — annual emissions testing retained across the Houston-area counties, safety inspection eliminated 1 Jan 2025. Older average fleet than DFW and slightly thinner independent tech density.', 'Run the same lost-walk-in question as DFW. Houston''s fleet is older, so expect more heavy repair and less light maintenance in the job mix they describe.'),
('Tampa-St. Petersburg, FL', 4, 'MCC — Tampa–St. Petersburg, FL  ·  Market #4', 'Tampa / Brandon / Seffner / Clearwater / St. Pete  ·  Hillsborough & Pinellas Counties', 'Florida has no state vehicle inspection of any kind — no safety, no emissions. There is no regulatory calendar creating demand. What drives it instead is an old fleet, a large retiree population that pays a premium for convenience, and low customer acquisition cost.', 'Do NOT reach for a compliance hook here — there isn''t one, and inventing one destroys credibility fast. The whole conversation rests on convenience economics. This market is the cleanest test of whether MCC works absent a regulatory forcing function, which makes it the most informative market on the list.'),
('Las Vegas, NV', 5, 'MCC — Las Vegas, NV  ·  Market #5', 'Las Vegas / Henderson / North Las Vegas / Summerlin  ·  Clark County', 'Clark County requires an annual emissions test for model-year 1968 and newer gasoline vehicles, tied directly to registration renewal. New cars are exempt for their first three registration cycles and hybrids for five model years. Repair waivers require documented spend at a licensed station.', 'Annual, registration-gated, and no new-car dilution past three years — this is the second-best recurring calendar on the list after Charlotte. Extreme car dependence and thin incumbent presence.'),
('Jacksonville, FL', 7, 'MCC — Jacksonville, FL  ·  Market #7', 'Jacksonville / Orange Park / Atlantic Beach  ·  Duval & Clay Counties', 'No Florida state inspection, same as Tampa. Jacksonville''s draw is that it is underserved — incumbent lead platforms have thin penetration and provider acquisition cost should be the lowest of any market on this list.', 'Cheapest market to acquire supply. If the bid-pack price objection shows up even here, that is a strong signal the pricing is wrong rather than the market.'),
('Charlotte, NC', 8, 'MCC — Charlotte, NC  ·  Market #8', 'Charlotte / Matthews / Huntersville / Indian Trail  ·  Mecklenburg County', 'North Carolina requires an annual safety inspection statewide on nearly every registered vehicle, and Mecklenburg is one of 19 counties that adds an annual emissions test on top. Under NC DEQ''s pending plan revision, Mecklenburg is the one county expected to keep emissions when the other 18 drop it.', 'The strongest ongoing regulatory calendar of the eight — every car, every year, gated on registration, with a second test layered on in Mecklenburg specifically. This is the closest analogue to the Atlanta thesis and the cleanest replication test.'),
('San Antonio, TX', 9, 'MCC — San Antonio, TX  ·  Market #9', 'San Antonio / Stone Oak / Selma / Schertz  ·  Bexar County', 'Bexar County joins the Texas emissions program on 1 Nov 2026 — roughly ten weeks out. Every gasoline vehicle roughly two to 24 model years old registered in Bexar will need a passing OBD-II emissions test before registration renewal, capped at $18.50. Local coverage has already flagged questions about whether the county has enough certified equipment and technicians to absorb the demand.', 'TIME-CRITICAL and the single best cold-call opening on this list. Shops are actively preparing right now — some have already bought analyzers. Maria is calling into a market where a brand-new recurring demand event is ten weeks away and nobody knows yet how it will shake out. Work this market FIRST.')
ON CONFLICT (market) DO NOTHING;

-- Seed: 130 prospects across 8 markets
INSERT INTO provider_call_prospects (
  market, row_number, business_name, segment, priority, city, county, address, phone,
  google_rating, review_count, screening_flags, why_this_one, contact_name,
  attempt_1, attempt_2, attempt_3, outcome, b1_send_bid, b2_fair_price, b2_price_unit,
  b3_bid_style, r3_yes_reason, r3_no_reason, bid_pack_pitched, what_they_said,
  c2_first_refusal, notes, caller
) VALUES
('Phoenix-Scottsdale, AZ', 1, 'Chases Mobile Mechanic', 'Mobile mechanic', 1, 'Scottsdale', 'Maricopa', 'Scottsdale, AZ 85257', '+1 707-230-9805', 4.8, 25, NULL, 'Chase; solo operator, open 24h, brakes/rotors/suspension; reviews stress honesty and price — classic lead-hungry profile', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 2, 'Big Shawn''s Auto Repair Mobile Services', 'Mobile mechanic', 1, 'Scottsdale', 'Maricopa', '2615 Hayden Rd, Scottsdale, AZ 85257', '+1 623-980-2116', 5.0, 13, NULL, 'Shawn; 7-day availability, does pre-purchase inspections — PPI work maps directly onto MCC job types', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 3, 'Ricos Mobile Mechanic', 'Mobile mechanic', 1, 'Phoenix', 'Maricopa', '4712 E Melvin St, Phoenix, AZ 85008', '+1 480-450-8846', 4.6, 9, NULL, 'Rico; open to 10pm, repeat-customer reviews, competes explicitly on price', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 4, 'Tempe Mobile Mechanic', 'Mobile mechanic', 2, 'Tempe', 'Maricopa', '1716 W 10th Pl, Tempe, AZ 85281', '+1 480-327-6988', 5.0, 2, 'Thin reviews', 'A/C compressor work; only two reviews so unproven, but likely receptive', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 5, 'Mullins Mobile Mechanics', 'Mobile mechanic', 3, 'Scottsdale', 'Maricopa', '5088 N 83rd St, Scottsdale, AZ 85250', '+1 480-708-2014', 5.0, 1, 'Thin reviews', 'Jason; single review — good warm-up dial, low stakes', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 6, 'Mobile Mechanic Pros Tempe', 'Mobile mechanic', 3, 'Tempe', 'Maricopa', '111 S Hardy Dr #4, Tempe, AZ 85281', '+1 480-418-4967', 3.9, 30, 'Low rating; lead-broker model', 'Reviews describe them subcontracting jobs out to bidders — already a marketplace, will benchmark MCC against it', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 7, 'Mobile Mechanic (Tempe)', 'Mobile mechanic', 3, 'Tempe', 'Maricopa', '822 S Ash Ave, Tempe, AZ 85281', '+1 623-755-9787', 3.0, 4, 'Low rating; no-show complaints', 'Daniel; would fail the bouncer threshold at scale — warm-up call only, do not pitch a pack', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 8, 'Gary''s Automotive Repair', 'Independent shop', 1, 'Chandler', 'Maricopa', '489 N Arizona Ave, Chandler, AZ 85225', '+1 480-656-8415', 4.8, 248, NULL, 'Ask for Benny; weekday-only, no weekend hours — capacity likely available', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 9, 'Innovative Automotive', 'Independent shop', 1, 'Chandler', 'Maricopa', '710 W Alamo Dr, Chandler, AZ 85225', '+1 480-660-0847', 5.0, 49, NULL, 'Mike + Alex; quotes by text, wins on price vs chains — fits bid-based flow naturally', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 10, 'Top Tech Automotive', 'Independent shop', 1, 'Chandler', 'Maricopa', '725 N Arizona Ave, Chandler, AZ 85225', '+1 480-247-3402', 4.9, 271, NULL, 'Chris is owner-operator and answers directly — decision-maker on first dial', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 11, 'Competitive Auto Repair', 'Independent shop', 1, 'Gilbert', 'Maricopa', '615 W Ray Rd Ste B, Gilbert, AZ 85233', '+1 602-989-3072', 4.8, 72, NULL, 'Jared / Camron; open Saturdays, name signals price positioning', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 12, 'SSC Auto Repair', 'Independent shop', 2, 'Chandler', 'Maricopa', '60 E Highland St, Chandler, AZ 85225', '+1 480-992-7200', 5.0, 116, NULL, 'Adam (manager), Christopher Acosta (service); referral pipeline from a Jeep shop already', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 13, 'Crawford''s Auto Repair', 'Independent shop', 2, 'Chandler', 'Maricopa', '450 E Frye Rd, Chandler, AZ 85225', '+1 480-201-0740', 4.8, 398, NULL, 'Ask for Ken; high review volume — may not feel a lead need', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 14, 'Mac''s Complete Auto Repair', 'Independent shop', 2, 'Chandler', 'Maricopa', '6948 W Chandler Blvd, Chandler, AZ 85226', '+1 480-709-6259', 5.0, 473, NULL, 'Mac / Javier / Steve; loaner cars offered — established, likely booked out', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 15, 'European Master Tech', 'Euro specialist', 1, 'Scottsdale', 'Maricopa', '9550 N 90th St Ste 102, Scottsdale, AZ 85258', '+1 602-412-7490', 5.0, 33, NULL, 'Arlen; BMW/Mini/Jaguar/VW, small shop with room to grow', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 16, 'Highline European', 'Euro specialist', 2, 'Scottsdale', 'Maricopa', '9175 E Pima Center Pkwy #3, Scottsdale, AZ 85258', '+1 480-246-2177', 5.0, 29, 'High-end exotic', 'Kyle; McLaren/Ferrari/AMG — very high ticket, probably not a bid-pack buyer but worth the data point', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 17, 'Advanced Import Specialist', 'Euro specialist', 3, 'Scottsdale', 'Maricopa', '9550 N 90th St, Scottsdale, AZ 85258', '+1 480-330-4057', 5.0, 4, 'Thin reviews', 'Henry; four reviews — warm-up dial', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 18, 'Beck''s European', 'Euro specialist', 2, 'Scottsdale', 'Maricopa', '8225 E Butherus Dr, Scottsdale, AZ 85260', '+1 480-556-6572', 4.8, 283, NULL, 'Frank / Nick; Porsche and Audi focus, established', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 19, 'Scottsdale European Service', 'Euro specialist', 3, 'Scottsdale', 'Maricopa', '7279 E Adobe Dr Ste 110, Scottsdale, AZ 85255', '+1 480-473-4722', 5.0, 1366, 'Very high volume', 'Carl / Karl / Zach; 1,366 reviews and takes walk-ins — almost certainly no lead need, ask anyway for the contrast', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 20, 'Jett''s Mobile Detailing & Ceramic Coatings', 'Mobile detailing', 1, 'Scottsdale', 'Maricopa', '15475 N Greenway Hayden Loop, Scottsdale, AZ 85260', '+1 602-691-6927', 5.0, 130, NULL, 'Kaleb (scheduling), Garrett/Grant (techs); same-day booking, multi-tech — can absorb volume', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 21, 'North Scottsdale Mobile Detailing', 'Mobile detailing', 1, 'Scottsdale', 'Maricopa', '14700 N Airport Dr Ste 150, Scottsdale, AZ 85260', '+1 602-540-6614', 4.8, 54, NULL, 'George, owner-operator with 1-2 helpers; 7 days, 7am-7:30pm', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 22, 'Hudson''s Mobile Detailing of Scottsdale', 'Mobile detailing', 2, 'Scottsdale', 'Maricopa', '16220 N Scottsdale Rd, Scottsdale, AZ 85254', '+1 480-520-3923', 5.0, 10, NULL, 'Ten reviews, open 24h listing — newer operator, likely wants leads', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 23, 'Camelback Mobile Car Detailing', 'Mobile detailing', 2, 'Scottsdale', 'Maricopa', '7001 N Scottsdale Rd, Scottsdale, AZ 85253', '+1 480-463-6903', 5.0, 8, 'Thin reviews', 'Enthusiast work (carbon fiber, hot-weather scheduling) — small but careful', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 24, 'Reed''s Mobile Detailing Scottsdale', 'Mobile detailing', 3, 'Scottsdale', 'Maricopa', '7628 E Indian School Rd, Scottsdale, AZ 85251', '+1 928-515-4435', 5.0, 5, 'Thin reviews', 'Five reviews — warm-up dial', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Phoenix-Scottsdale, AZ', 25, 'K Crown Mobile Car Detailing Old Town', 'Mobile detailing', 3, 'Scottsdale', 'Maricopa', '4000 N Drinkwater Blvd, Scottsdale, AZ 85251', '+1 602-641-3578', 5.0, 4, 'Thin reviews; no hours listed', 'Old Town / Fashion Square catchment — warm-up dial', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 1, 'Mobile Mechanic (Frisco Square)', 'Mobile mechanic', 1, 'Frisco', 'Collin', '6136 Frisco Square Blvd Ste 487, Frisco, TX 75034', '+1 888-391-6324', 4.8, 12, 'Toll-free number — may be a dispatch layer', 'Ask for Rocky or Alex; one review alleges heavy price gouging vs Firestone — probe pricing model carefully', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 2, 'Northrich Automotive', 'Independent shop', 1, 'Richardson', 'Dallas', '1315 Executive Dr W, Richardson, TX 75081', '+1 972-669-9990', 4.8, 757, NULL, 'Dustin / Aaron / Eric / Ryan; family-owned 25+ yrs, offers Uber rides home — already invests in convenience', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 3, 'Wayne Motors LLC', 'Independent shop', 1, 'Dallas', 'Collin', '17800 Dickerson St Ste 100, Dallas, TX 75252', '+1 214-717-9999', 5.0, 30, NULL, 'Jason, master certified, presents options rather than upselling — 30 reviews means real lead appetite', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 4, 'The Auto Pro Shop', 'Independent shop', 1, 'Richardson', 'Dallas', '670 James Dr, Richardson, TX 75080', '+1 972-699-9405', 4.6, 124, NULL, 'Ask for Ray; open Saturdays, family-referral driven', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 5, 'Innovative Auto Works', 'Independent shop', 1, 'Plano', 'Collin', '2815 Premier Dr, Plano, TX 75075', '+1 972-424-2828', 4.7, 109, NULL, 'Rick; does custom/lowering work alongside repair — broad job acceptance', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 6, 'Adjustable Auto Body Repair', 'Independent shop', 2, 'Richardson', 'Dallas', '201 N Central Expy, Richardson, TX 75080', '+1 972-799-6031', 4.9, 145, 'Body/collision — insurance-driven', 'Angelo; collision work runs through insurers, so bid flow may not fit — worth testing', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 7, 'Christensen Tire & Automotive', 'Independent shop', 2, 'Richardson', 'Dallas', '1407 E Belt Line Rd, Richardson, TX 75081', '+1 972-234-8852', 4.7, 652, 'Tire-led', 'Open 7 days; high volume, tire-anchored — may not need leads', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 8, 'EurAuto Shop', 'Euro specialist', 1, 'Plano', 'Collin', '4008 W Plano Pkwy, Plano, TX 75093', '+1 214-552-4194', 4.9, 621, NULL, 'Shark / Jon / Michael; does remote pre-purchase inspections for out-of-state buyers — already sells a concierge-shaped service', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 9, 'Tommy''s European Service & Repair', 'Euro specialist', 1, 'Plano', 'Collin', '1100 Summit Ave #106, Plano, TX 75074', '+1 972-954-6362', 4.7, 277, NULL, 'Matt Howard responds in minutes and offers loaners — fast-quote culture fits bidding', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 10, 'Dallas European Auto', 'Euro specialist', 2, 'Plano', 'Collin', '605 Digital Dr, Plano, TX 75075', '+1 972-944-5557', 4.8, 466, NULL, 'Robert (owner), Adam, Amir, Shahab; strong PPI business', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 11, 'Autoscope European Car Care', 'Euro specialist', 2, 'Plano', 'Collin', '601 Coit Rd, Plano, TX 75075', '+1 972-867-7467', 4.8, 805, 'Very high volume', 'Melissa; free delivery/pickup and loaners already — established, low lead need', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 12, 'European Auto Tech', 'Euro specialist', 3, 'Plano', 'Collin', '3953 N Central Expy, Plano, TX 75023', '+1 972-422-9941', 4.2, 62, 'Low rating', 'Arthur/Arturo; open 7 days including Sunday — unusual availability, but rating is below the bouncer line', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 13, 'Frisco Mobile Detailing', 'Mobile detailing', 1, 'Frisco', 'Denton', '1588 Castle Pines Dr, Frisco, TX 75036', '+1 469-600-5988', 4.9, 115, NULL, 'Antonio + Logan; ceramic and paint correction, texts customers directly', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 14, 'Big Steps Mobile Detailing', 'Mobile detailing', 1, 'Frisco', 'Denton', '5570 FM 423 #250, Frisco, TX 75034', '+1 469-536-7995', 5.0, 109, NULL, 'Russell; repeat multi-vehicle clients, easy scheduling', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 15, 'Mobile Detailing Frisco', 'Mobile detailing', 1, 'Frisco', 'Denton', '4770 Teel Pkwy, Frisco, TX 75034', '+1 516-606-6129', 5.0, 95, NULL, 'Mahdi; paint correction and ceramic, returns free to redo work — quality signal', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 16, 'LUMEX Mobile Car Detailing LLC', 'Mobile detailing', 2, 'Frisco', 'Collin', '9605 Gaylord Pkwy, Frisco, TX 75035', '+1 609-513-9958', 5.0, 17, NULL, 'Vlad; covers Frisco/Plano/McKinney — wide radius, newer, wants volume', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 17, 'The Mobile Detailer Frisco', 'Mobile detailing', 3, 'Frisco', 'Denton', '6475 All Stars Ave, Frisco, TX 75033', '+1 214-300-9222', 4.9, 27, 'Review content mismatch — several reviews describe junk removal, not detailing', 'Listing quality is suspect; verify what they actually do before pitching', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Dallas-Fort Worth, TX', 18, 'Supreme Mobile Car Detailing Plano', 'Mobile detailing', 3, 'Plano', 'Collin', '1709 USA Dr, Plano, TX 75025', '+1 432-666-2124', 5.0, 4, 'Thin reviews; area-code mismatch (432 = West TX)', 'Warm-up dial; confirm they are actually local', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 1, 'Mobile Mechanic Christian', 'Mobile mechanic', 1, 'Tomball', 'Harris', '21511 Henrys Blush Dr, Tomball, TX 77377', '+1 806-315-0557', 4.7, 236, NULL, 'Christian runs a small team (tech Roy named in reviews); 236 reviews is the deepest mobile track record in this market', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 2, 'Peace Mobile Mechanic Services', 'Mobile mechanic', 1, 'Houston', 'Harris', '10802 Paulus Dr Ste 3, Houston, TX 77041', '+1 713-474-4104', 4.9, 38, NULL, 'Wilber; works late nights, covers Katy — flexible on dispatch windows', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 3, 'Corb''s Auto Repair LLC', 'Independent shop', 1, 'Cypress', 'Harris', '12802 Grant Rd, Cypress, TX 77429', '+1 281-320-9784', 4.9, 265, NULL, 'Chris + Lisa at the desk; honored a warranty free of charge and waived an inspection fee — strong service ethic', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 4, 'Nolls Auto Repair', 'Independent shop', 1, 'Cypress', 'Harris', '17215 Houston Dr, Cypress, TX 77433', '+1 281-758-4212', 4.8, 165, NULL, 'Weekday-only, beats competitor quotes by wide margins — price-competitive, capacity likely', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 5, 'Cypress Auto Repair', 'Independent shop', 1, 'Cypress', 'Harris', '13620 Cypress North Houston Rd, Cypress, TX 77429', '+1 281-807-1112', 4.6, 66, NULL, 'Ali; open Saturdays, 66 reviews — smallest of the Cypress cluster, most likely to want leads', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 6, 'Lucas Auto Care', 'Independent shop', 2, 'Cypress', 'Harris', '12600 Grant Rd, Cypress, TX 77429', '+1 281-379-5800', 4.9, 1152, 'Very high volume', 'Chris / Ryan; includes shuttle and car wash, works Maserati/BMW/Audi — 1,152 reviews, low lead need', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 7, 'European Motor Gruppe', 'Euro specialist', 1, 'Houston', 'Harris', '6513 Atwell Dr, Houston, TX 77081', '+1 832-742-8105', 5.0, 167, NULL, 'Mike (tech/owner), Erika (scheduling); BMW-heavy, explicitly avoids inflating repair bills', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 8, 'European Auto Specialist & Collision', 'Euro specialist', 1, 'Houston', 'Harris', '3415 Fondren Rd, Houston, TX 77063', '+1 832-868-4954', 4.9, 136, NULL, 'Ned (owner) + Anthony; handles exotics and does key replacement — broad service menu', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 9, 'European Cars Limited', 'Euro specialist', 2, 'Houston', 'Harris', '4601 Feagan St Ste A, Houston, TX 77007', '+1 713-370-2730', 4.9, 224, NULL, 'Phil (40 yrs, owner) + Betty; accepts customer-supplied parts — unusually flexible', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 10, 'Today''s European Cars', 'Euro specialist', 2, 'Houston', 'Harris', '6261 Richmond Ave Ste E, Houston, TX 77057', '+1 713-781-7449', 4.9, 553, 'Recent ownership change', 'Thomas + Ben; reviews reference a new owner — transitions often mean appetite for new channels', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 11, 'JR Mobile Detailing', 'Mobile detailing', 1, 'Katy', 'Harris', '5335 E 5th St Unit 304, Katy, TX 77493', '+1 346-464-2205', 5.0, 256, NULL, 'Jason runs a team with dispatched techs — 256 reviews, real operational capacity', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 12, 'On-The-Go Mobile Detailing', 'Mobile detailing', 1, 'Katy', 'Fort Bend', '29511 Cherry Vine Rd, Katy, TX 77494', '+1 832-230-2326', 5.0, 75, NULL, 'Chris; does fleet/office visits — already thinks in multi-vehicle jobs', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 13, 'Prairie Gloss Mobile Car Detailing', 'Mobile detailing', 2, 'Katy', 'Harris', '5722 1st St, Katy, TX 77493', '+1 956-300-4705', 4.9, 60, NULL, 'Xavier + Sumit; odor removal and ceramic, books around customer work hours', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 14, 'Lumen Mobile Detailing', 'Mobile detailing', 2, 'Katy', 'Fort Bend', '29655 Jordan Crossing Blvd, Katy, TX 77494', '+1 832-736-0402', 5.0, 12, 'New business', 'Ross; reviews describe him canvassing door-to-door with hang tags — actively buying customer acquisition already', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Houston, TX', 15, 'Katy Elite Mobile Car Detailing', 'Mobile detailing', 3, 'Katy', 'Fort Bend', '2717 Commercial Center Blvd, Katy, TX 77494', '+1 832-626-0831', 5.0, 15, 'Thin reviews', 'Warm-up dial', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 1, 'Simple Solutions Mobile Mechanic', 'Mobile mechanic', 1, 'Valrico', 'Hillsborough', '3307 Summer Island Ct, Valrico, FL 33594', '+1 813-541-6114', 4.9, 260, 'Recent responsiveness complaint (Jun 2026)', 'Jay + Z; 260 reviews, but one 2026 review says calls/texts stopped being returned — confirm they are still active', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 2, 'Marc''s Mobile Auto Care', 'Mobile mechanic', 1, 'Seffner', 'Hillsborough', '1431 S Kingsway Rd, Seffner, FL 33584', '+1 731-358-1045', 5.0, 185, 'Closed Fridays', 'Marc; does turbo installs and multi-day jobs at the customer''s home, offers a warranty', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 3, 'Mobile Mechanic (Tampa Heights)', 'Mobile mechanic', 2, 'Tampa', 'Hillsborough', '213 W Emily St, Tampa, FL 33603', '+1 813-308-0288', 4.4, 97, 'Low rating; pricing complaints', 'Dave / Anthony / Paul named as techs — dispatch model. $200 for a jump start drew a complaint; probe pricing', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 4, 'Unique Automotive Repair, Inc.', 'Independent shop', 1, 'Tampa', 'Hillsborough', '1717 E Busch Blvd Ste 909, Tampa, FL 33612', '+1 813-401-5352', 5.0, 164, NULL, 'Albert; owner-operator, gets referrals from a Jeep Facebook group — already sourcing leads socially', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 5, 'Auto Repair Center', 'Independent shop', 1, 'Tampa', 'Hillsborough', '7101 N 40th St, Tampa, FL 33604', '+1 813-443-4730', 4.9, 84, NULL, 'Carlos; offers payment plans and Saturday hours — 84 reviews, wants volume', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 6, 'Tampa Auto Doctor', 'Independent shop', 2, 'Tampa', 'Hillsborough', '6840 S MacDill Ave, Tampa, FL 33611', '+1 813-474-4330', 4.9, 409, 'One detailed repeat-repair complaint', 'Jessica / Luis / Joel; takes walk-ins, South Tampa catchment', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 7, 'AutoWorks of Tampa', 'Independent shop', 2, 'Tampa', 'Hillsborough', '5507 N Nebraska Ave, Tampa, FL 33604', '+1 813-536-6669', 4.7, 1118, 'Very high volume', 'Corey / Kevin; sister shop to Heights Auto Imports, online booking already — low lead need but good process intel', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 8, 'One Stop Automotive Repair', 'Independent shop', 3, 'Tampa', 'Hillsborough', '3602 N Florida Ave, Tampa, FL 33603', NULL, 4.6, 75, 'NO PHONE ON LISTING', 'Vince (owner), Michael Smith (tech); open to 8pm. Phone must be sourced before dialing', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 9, 'Heights Auto Imports', 'Euro specialist', 1, 'Tampa', 'Hillsborough', '6309 N Florida Ave, Tampa, FL 33604', '+1 813-443-5353', 5.0, 259, NULL, 'Teresa (front), Kyle and Ray (techs); Porsche/Audi/VW. A review notes a customer found them by asking an AI for the best shop — they already benefit from algorithmic referral', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 10, 'Euro Imports Auto Repair', 'Euro specialist', 1, 'Clearwater', 'Pinellas', '1141 Court St, Clearwater, FL 33756', '+1 727-238-8991', 5.0, 68, NULL, 'Luis (owner), JD and Mike; same-day intake, 68 reviews — room to grow', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 11, 'European Import Specialist', 'Euro specialist', 2, 'St. Petersburg', 'Pinellas', '3700 5th Ave N, St. Petersburg, FL 33713', '+1 727-454-8531', 4.9, 302, 'One serious scope-of-work dispute', 'Geri (owner); open 7 days including Sunday — unusual availability for a Euro shop', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 12, 'European Performance', 'Euro specialist', 2, 'St. Petersburg', 'Pinellas', '930 4th Ave N, St. Petersburg, FL 33705', '+1 727-823-4685', 4.9, 397, NULL, 'Bill (service manager); ~40 yrs in business, Porsche-heavy, mid-renovation', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 13, 'Legit Mobile Detailing', 'Mobile detailing', 1, 'Tampa', 'Hillsborough', '4207 S Dale Mabry Hwy, Tampa, FL 33611', '+1 413-405-1213', 4.9, 63, NULL, 'Nasser; next-day turnaround on emergency details, walks through options on site', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 14, 'Fred''s Mobile Detailing', 'Mobile detailing', 1, 'Tampa', 'Hillsborough', '201 N Franklin St, Tampa, FL 33602', '+1 813-635-6160', 4.8, 99, NULL, 'Fred runs a team; also does jump starts — already blurring detail and roadside, which is exactly MCC''s job spread', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Tampa-St. Petersburg, FL', 15, 'Clean Machine Mobile Detailing', 'Mobile detailing', 2, 'St. Petersburg', 'Pinellas', '1100 Newton Ave S, St. Petersburg, FL 33705', '+1 727-906-6961', 5.0, 71, NULL, 'Tim, solo operator; works Sundays, does ozone odor treatment', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 1, 'Rush Mobile Mechanic LLC', 'Mobile mechanic', 1, 'Las Vegas', 'Clark', '1000 Dumont Blvd, Las Vegas, NV 89169', '+1 702-439-7961', 5.0, 30, NULL, 'Sean; same-day booking, has done 2am oil changes, does pre-purchase inspections — 24h market fit is real here', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 2, 'Matt''s Mobile Mechanic and Welding', 'Mobile mechanic', 1, 'Las Vegas', 'Clark', '4711 Boulder Hwy, Las Vegas, NV 89121', '+1 702-849-1295', 4.7, 42, NULL, 'Matt; works in extreme heat, competes hard on price, welding is a differentiated capability', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 3, 'Auto Medic Mobile Mechanics', 'Mobile mechanic', 2, 'Henderson', 'Clark', '1945 Whitney Mesa Dr, Henderson, NV 89014', '+1 702-273-6773', 4.6, 168, 'Significant RV/coach mix', 'Ryan / Shane / Russ; has both a shop and mobile units — hybrid model, good comparison data', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 4, 'On the Spot Mobile Mechanic and RV Specialist', 'Mobile mechanic', 3, 'North Las Vegas', 'Clark', '2842 E Reynolds Ave, North Las Vegas, NV 89030', '+1 702-913-4985', 5.0, 31, 'Primarily RV', 'Tyler Austin; reviews are almost entirely motorhome work — may be out of scope', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 5, 'H-TECH Car Repair', 'Independent shop', 1, 'Las Vegas', 'Clark', '2069 S Rainbow Blvd, Las Vegas, NV 89146', '+1 702-685-1400', 4.9, 166, NULL, 'Joedan / Bernard / Pete; repeatedly beats competitor quotes by 4-5x margins — aggressive on price, needs volume', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 6, 'Angie''s Auto Service', 'Independent shop', 1, 'Henderson', 'Clark', '520 W Sunset Rd Ste 8, Henderson, NV 89011', '+1 725-247-5832', 5.0, 24, NULL, 'Aaron, Sharon, Antony, tech Jose; open Saturdays, only 24 reviews — newest and hungriest shop in Henderson', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 7, 'Asian Imports Auto', 'Independent shop', 2, 'Henderson', 'Clark', '1025 American Pacific Dr, Henderson, NV 89074', '+1 702-685-9500', 4.7, 474, NULL, 'Nick; sends text diagnoses with full price breakdowns — process already matches a bid flow', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 8, 'Integrity Customs', 'Independent shop', 2, 'Henderson', 'Clark', '253 Elliott Rd Ste 9, Henderson, NV 89011', '+1 702-510-4375', 4.9, 133, 'Body/cosmetic focus', 'Joe/Joey; dent, scratch, bumper and body panel work — cosmetic category, multiple locations', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 9, 'European House For Imports', 'Euro specialist', 1, 'Las Vegas', 'Clark', '10177 W Charleston Blvd E, Las Vegas, NV 89135', '+1 702-341-0100', 4.8, 197, NULL, 'Josh + Michelle; Summerlin, does free small fixes to win relationships — relationship-first, will hear the pitch out', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 10, 'Desert Oasis European Auto Service', 'Euro specialist', 2, 'Las Vegas', 'Clark', '2079 S Rainbow Blvd, Las Vegas, NV 89146', '+1 702-255-4090', 4.7, 559, NULL, 'Anthony (service mgr), Bill, Shelina, Diane; tucked at the back of the lot — visibility is a known problem for them', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 11, 'All European I Auto Repair', 'Euro specialist', 2, 'Las Vegas', 'Clark', '7010 W Russell Rd #A, Las Vegas, NV 89113', '+1 702-363-9191', 4.6, 476, NULL, 'Kris/Chris, Chad, Johnny, master tech Derrick; offers courtesy rides', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 12, 'European Motor Cars', 'Euro specialist', 2, 'Las Vegas', 'Clark', '3440 Spring Mountain Rd, Las Vegas, NV 89102', '+1 702-367-7140', 4.6, 697, 'Very high volume', 'Shelina (owner), Jose Guerrero (advisor); courtesy shuttle — established', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 13, 'Sin City Mobile Detailing', 'Mobile detailing', 1, 'Henderson', 'Clark', '631 N Stephanie St, Henderson, NV 89014', '+1 702-530-5743', 4.9, 376, NULL, 'Elicio, Ismael named as techs; 376 reviews, same-day Yelp response — already paying for lead flow somewhere', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 14, 'Mobile Auto Spa', 'Mobile detailing', 1, 'Las Vegas', 'Clark', '3021 S Valley View Blvd Ste 207, Las Vegas, NV 89102', '+1 702-600-2411', 4.9, 138, NULL, 'Brendeen/Branden (owner), Dakoda; ceramic coating, 7 days, offers a 24h rain guarantee', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Las Vegas, NV', 15, 'Tornado Mobile Detailing LLC', 'Mobile detailing', 1, 'Las Vegas', 'Clark', '840 S Rancho Dr, Las Vegas, NV 89106', '+1 725-277-2583', 4.9, 110, NULL, 'Wayne + Ashley (couple), Tony; next-day booking, fixed another company''s botched job — reliable backup capacity', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 1, 'Simple Mobile Mechanic Jacksonville', 'Mobile mechanic', 1, 'Jacksonville', 'Duval', '2695 Post St, Jacksonville, FL 32204', '+1 912-602-1933', 4.6, 58, 'GA area code', 'Ty (tech) and Cam (scheduling); flexible scheduling and works to a customer''s budget', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 2, 'Pedroso Solutions LLC Mobile Mechanic', 'Mobile mechanic', 1, 'Jacksonville', 'Duval', '8681 A C Skinner Pkwy Apt 518, Jacksonville, FL 32256', '+1 917-215-6633', 5.0, 37, 'NY area code', 'Pedro; does remote pre-purchase inspections for out-of-state buyers — concierge-shaped work already', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 3, 'North Florida Mobile Mechanic & Auto Services', 'Mobile mechanic', 1, 'Jacksonville', 'Duval', '3623 Owen Ave, Jacksonville, FL 32208', '+1 904-749-2141', 5.0, 24, NULL, 'Kolby and his father-in-law; growing a young business, reviews explicitly mention wanting support', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 4, 'Nep''s Mobile Mechanics', 'Mobile mechanic', 3, 'Jacksonville', 'Duval', '8808 Beach Blvd, Jacksonville, FL 32216', '+1 229-345-4277', 5.0, 4, 'Thin reviews; GA area code', 'Keyon; four reviews — warm-up dial', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 5, 'JSE Auto Care', 'Independent shop', 1, 'Orange Park', 'Clay', '2175 Kingsley Ave Ste 212, Orange Park, FL 32073', '+1 904-883-8840', 5.0, 62, NULL, 'Susan (communications), Garcia and Amauris (techs); open Saturdays, competes on price', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 6, 'Hill Automotive Inc.', 'Independent shop', 1, 'Orange Park', 'Clay', '234 Industrial Loop S, Orange Park, FL 32073', '+1 904-269-6777', 4.8, 96, NULL, 'Quoted a job in two minutes over the phone at a fraction of a competitor — fast quoting suits bidding', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 7, 'Miller''s Automotive', 'Independent shop', 1, 'Orange Park', 'Clay', '1156 Park Ave, Orange Park, FL 32073', '+1 904-213-1180', 4.9, 387, NULL, 'Ted Miller; sends photo and video inspection reports with tiered estimates — sophisticated process', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 8, 'JJ Auto Service & Tires', 'Independent shop', 2, 'Orange Park', 'Clay', '19 Blanding Blvd, Orange Park, FL 32073', '+1 904-621-2126', 4.8, 742, NULL, 'John Hummel, Johnny, Billy, Shannon, Matthew; 742 reviews — established', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 9, 'Automotive Specialists', 'Independent shop', 3, 'Orange Park', 'Clay', '120 College Dr, Orange Park, FL 32065', '+1 904-276-2769', 4.4, 240, 'Low rating; multiple billing disputes', 'Dennis (owner), Tommy (lead tech). Several detailed complaints about work not completed as billed — below the bouncer line', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 10, 'Deutschwerks European Auto', 'Euro specialist', 1, 'Jacksonville', 'Duval', '205 Stockton St, Jacksonville, FL 32204', '+1 904-348-0049', 5.0, 111, NULL, 'Joe + Bella; sends text-based estimates — already quoting the way MCC bids', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 11, 'Eurofed Automotive', 'Euro specialist', 2, 'Jacksonville', 'Duval', '8864 Atlantic Blvd, Jacksonville, FL 32211', '+1 904-977-8558', 4.9, 496, 'Multi-location chain', 'Matt; part of a regional group — decision may sit above the location manager', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 12, 'Argos European Car Care', 'Euro specialist', 2, 'Jacksonville', 'Duval', '14600 Duval Pl W #43, Jacksonville, FL 32218', '+1 904-734-7573', 4.8, 221, 'One repeat-repair dispute', 'Also sells cars; works alongside other Euro shops rather than competing — open to partnership framing', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 13, 'Bavarian Rennsport', 'Euro specialist', 2, 'Atlantic Beach', 'Duval', '2027 Mayport Rd, Jacksonville, FL 32233', '+1 904-270-9390', 4.8, 689, 'Exotic/high-end', 'Shawn, Cade; Lamborghini/Porsche work, open to 7pm, 2yr/24k warranty', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Jacksonville, FL', 14, 'Her Touch Mobile Detailing LLC', 'Mobile detailing', 1, 'Jacksonville', 'Duval', '5116 Gate Pkwy N, Jacksonville, FL 32256', '+1 904-637-9135', 5.0, 105, NULL, 'Abby + Ayden; only high-review mobile detailer surfaced in this market — the detailing segment here is thin, which is itself a finding', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 1, 'Longo Mobile Mechanic', 'Mobile mechanic', 1, 'Charlotte', 'Mecklenburg', '1418 Briar Creek Rd, Charlotte, NC 28205', '+1 704-798-7937', 4.9, 58, NULL, 'Longo; answers at 9pm, same-day turnarounds, works on high-end cars — strongest mobile profile in the market', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 2, 'Mobile-CAR Complete Auto Repair', 'Mobile mechanic', 1, 'Indian Trail', 'Union', '3006 Sardis Dr, Indian Trail, NC 28079', '+1 704-882-0577', 5.0, 69, 'Union County — also an emissions county', 'Jose; 10+ year customer relationships, weekday hours only', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 3, 'Mobile Mechanic (Ballantyne)', 'Mobile mechanic', 2, 'Charlotte', 'Mecklenburg', '14446 Adair Manor Ct, Charlotte, NC 28277', NULL, 5.0, 59, 'NO PHONE ON LISTING', 'Ivan; carries a full diagnostic computer and handles electronic parking brake systems. Phone must be sourced before dialing', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 4, 'Auto Shop of the Carolinas', 'Independent shop', 1, 'Charlotte', 'Mecklenburg', '234 E Cama St, Charlotte, NC 28217', '+1 704-525-3092', 4.9, 490, 'One billing dispute', 'Rozel; will re-check a car for free after a repair — relationship-oriented', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 5, 'Autoworks Unlimited Inc.', 'Independent shop', 1, 'Huntersville', 'Mecklenburg', '15316 N Old Statesville Rd, Huntersville, NC 28078', '+1 704-875-2929', 4.8, 76, 'Closed Fri/Sat/Sun', 'Dale; 20-year customer relationships but only 76 reviews and a four-day week — capacity is there', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 6, 'Auto Specialties of Lake Norman', 'Independent shop', 1, 'Huntersville', 'Mecklenburg', '100 Center Ln, Huntersville, NC 28078', '+1 704-201-7334', 4.7, 356, NULL, 'Burt/Bert; explicitly does state inspections — the annual NC inspection is their front door, so the calendar hook lands hardest here', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 7, 'Independent Tire and Auto Repair', 'Independent shop', 2, 'Charlotte', 'Mecklenburg', '3655 Beatties Ford Rd, Charlotte, NC 28216', '+1 704-398-0271', 4.5, 197, 'Customer service complaints', 'Fernando (owner), Jose; open Saturdays, serves a wide catchment', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 8, 'Intermind Automotive Group LLC', 'Independent shop', 3, 'Charlotte', 'Mecklenburg', '6910 Old Statesville Rd A, Charlotte, NC 28269', '+1 704-900-7203', 4.3, 96, 'Low rating; workmanship complaint', 'Mel, TJ; open Saturdays. Below the bouncer line — survey only, do not pitch a pack', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 9, 'Euro Cars Southend', 'Euro specialist', 1, 'Charlotte', 'Mecklenburg', '2429 S Tryon St, Charlotte, NC 28203', '+1 980-819-9230', 4.9, 711, NULL, 'Alex, Dillon; quotes over the phone and beats competitors, accepts customer-supplied parts — flexible', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 10, 'EU Auto', 'Euro specialist', 1, 'Charlotte', 'Mecklenburg', '315 Quincey St, Charlotte, NC 28203', '+1 980-322-8009', 4.9, 109, NULL, 'Paul (senior tech) + Ethan; Mercedes specialists, will look at a car same-day on a phone call', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 11, 'Premier Imports of Charlotte', 'Euro specialist', 2, 'Charlotte', 'Mecklenburg', '2513 Allen Rd S, Charlotte, NC 28269', '+1 980-207-4963', 4.6, 109, 'One parts-availability dispute', 'Felix (owner); explains cost drivers up front including card fees — transparent on economics', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 12, 'Import Connection', 'Euro specialist', 3, 'Charlotte', 'Mecklenburg', '5320 Monroe Rd, Charlotte, NC 28205', '+1 704-535-3598', 4.4, 62, 'Low rating; single-mechanic bottleneck; pricing complaints', 'Don (front desk); reviews describe one mechanic doing all the work and long waits — capacity-constrained, not lead-constrained', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 13, 'All Shine No Grime Mobile Auto Detailing', 'Mobile detailing', 1, 'Charlotte', 'Mecklenburg', '14119 Whistling Duck Ct, Charlotte, NC 28273', '+1 704-907-0623', 4.9, 245, NULL, 'Chris (scheduling), Josh (tech); tiered packages, will move an appointment up when a slot opens — flexible dispatch', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('Charlotte, NC', 14, 'The True Touch Mobile Detailing', 'Mobile detailing', 1, 'Charlotte', 'Mecklenburg', '10135 Wedge Ct, Charlotte, NC 28277', '+1 704-763-0752', 5.0, 140, NULL, 'Chris; online booking already in place, communicates ahead of every appointment', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 1, 'McDougall''s Mobile Mechanic', 'Mobile mechanic', 1, 'San Antonio', 'Bexar', '4582 Lark Ave, San Antonio, TX 78228', '+1 210-848-6100', 4.9, 76, NULL, 'Gary; does pre-purchase inspections and diesel work, 24h availability — best mobile profile in the market', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 2, 'DA Mobile Mechanic', 'Mobile mechanic', 1, 'San Antonio', 'Bexar', '1604 & US Hwy 281 N, San Antonio, TX 78259', '+1 210-847-1329', 4.9, 28, NULL, 'Daniel; arrives within the hour, takes varied payment methods, serves the Stone Oak corridor', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 3, 'Turtle''s Mobile Mechanic', 'Mobile mechanic', 3, 'San Antonio', 'Bexar', '5255 Walzem Rd, San Antonio, TX 78218', '+1 726-246-3209', 5.0, 2, 'Thin reviews', 'Two reviews, one very detailed — warm-up dial', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 4, 'Thousand Oaks Automotive', 'Independent shop', 1, 'San Antonio', 'Bexar', '2555 Thousand Oaks Dr, San Antonio, TX 78232', '+1 210-495-1100', 4.7, 797, NULL, 'Paul Sharp (advisor); explicitly low-pressure on recommendations. 797 reviews but ask the Nov 1 question — they will have a view on capacity', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 5, 'Ibarra Auto Repairs', 'Independent shop', 1, 'San Antonio', 'Bexar', '12743 Nacogdoches Rd, San Antonio, TX 78217', '+1 210-709-6904', 4.8, 79, 'One recent complaint about unreturned calls', 'Enrique (owner), Velia (office), Jacobo, Héctor; open Saturdays, accepts customer-supplied parts', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 6, 'Leodin Auto Repair', 'Independent shop', 1, 'San Antonio', 'Bexar', '10427 Perrin Beitel Ste 113, San Antonio, TX 78217', '+1 210-383-0961', 5.0, 22, NULL, 'Polo; small shop, 22 reviews, reviews say business is picking up fast — growth-stage, most likely to buy leads', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 7, 'Cornerstone Automotive', 'Independent shop', 3, 'San Antonio', 'Bexar', '14630 Blanco Rd, San Antonio, TX 78216', '+1 210-479-1901', 4.4, 114, 'Low rating; hostile phone-manner complaints; refuses vehicles over 20 yrs old', 'Harry; two recent reviews describe rude handling of pricing questions. Age cutoff is notable — Bexar''s new rule targets 2-24 model year cars', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 8, 'European Auto Werks', 'Euro specialist', 1, 'San Antonio', 'Bexar', '310 W Nakoma Dr, San Antonio, TX 78216', '+1 210-366-3248', 4.9, 55, NULL, 'Chris (owner), Scott, Barbara; Mercedes/Volvo, referred by the MB dealership itself — strong reputation, only 55 reviews', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 9, 'Foreign Specialists', 'Euro specialist', 2, 'San Antonio', 'Bexar', '110 E Rhapsody Dr, San Antonio, TX 78216', '+1 210-344-4420', 4.7, 17, 'Thin reviews', 'Rick; Volvo/Jaguar, gives free honest assessments including ''don''t fix this car'' — unusually candid', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 10, 'Import Auto Repair', 'Euro specialist', 2, 'San Antonio', 'Bexar', '2575 MacArthur View, San Antonio, TX 78217', '+1 210-655-8824', 4.7, 15, 'Thin reviews; no hours listed', 'Stan; decades of Mercedes work, entirely word-of-mouth — no marketing channel at all, which is the opportunity', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 11, 'Import Euroworks LLC', 'Euro specialist', 3, 'Selma', 'Bexar/Guadalupe', '16685 I-35, Selma, TX 78154', '+1 210-637-1211', 4.4, 209, 'Low rating; misdiagnosis dispute', 'Paco; fast and communicative per positive reviews, but a detailed misdiagnosis complaint sits below the bouncer line', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 12, 'MaxCraft Mobile Detailing', 'Mobile detailing', 1, 'San Antonio', 'Bexar', '20630 View Meadow, San Antonio, TX 78258', '+1 210-296-0593', 5.0, 324, NULL, 'Max, Logan; online booking, monthly plans, ceramic coating — 324 reviews and a subscription model already', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 13, 'Exodo Mobile Detailing', 'Mobile detailing', 1, 'San Antonio', 'Bexar', '235 Fair Ave, San Antonio, TX 78223', '+1 210-668-3328', 5.0, 26, NULL, 'Gael; enthusiast clientele, 24h listing, affordable positioning — growth-stage', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria'),
('San Antonio, TX', 14, 'World Is Yours Mobile Auto Detailing', 'Mobile detailing', 2, 'San Antonio', 'Bexar', '24902 Ima Ruth Pkwy, San Antonio, TX 78257', '+1 726-228-1733', 5.0, 17, NULL, 'Jason Giron; classic-car work, will come out within the hour', NULL, NULL, NULL, NULL, 'Not attempted', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Maria')
ON CONFLICT (market, row_number) DO NOTHING;
