// Drift guard for the BGC per-employee price.
//
// lib/bgc-pricing.json is THE single source of truth. Two derived
// surfaces consume it:
//   • lib/bgc-pricing.js  — Node twin (require()s the JSON directly,
//                            so it can never drift).
//   • www/bgc-pricing.js  — browser twin, GENERATED by
//                            scripts/generate-bgc-pricing.js.
//
// This test re-runs the generator into a buffer and asserts the
// on-disk www/bgc-pricing.js matches byte-for-byte. It also asserts
// that lib/bgc-pricing.js exposes the same display value. If either
// check fails, someone hand-edited a generated file or forgot to run
// `npm run generate:bgc-pricing` after bumping the JSON.

'use strict';

const fs = require('fs');
const path = require('path');
const assert = require('assert');

const REPO_ROOT = path.resolve(__dirname, '..', '..');

let pass = 0;
let fail = 0;
function test(name, fn) {
  try {
    fn();
    console.log(`  ok  ${name}`);
    pass++;
  } catch (err) {
    console.error(`  FAIL ${name}: ${err.message}`);
    fail++;
  }
}

const pricing = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'lib', 'bgc-pricing.json'), 'utf8'));
const { BGC_PRICE_DISPLAY } = require(path.join(REPO_ROOT, 'lib', 'bgc-pricing'));
const { build } = require(path.join(REPO_ROOT, 'scripts', 'generate-bgc-pricing'));
const onDiskBrowser = fs.readFileSync(path.join(REPO_ROOT, 'www', 'bgc-pricing.js'), 'utf8');
const expectedBrowser = build(pricing.display);

test('lib/bgc-pricing.json defines a non-empty "display" string', () => {
  assert.strictEqual(typeof pricing.display, 'string');
  assert.ok(pricing.display.length > 0, 'display must be non-empty');
});

test('lib/bgc-pricing.js BGC_PRICE_DISPLAY matches the JSON', () => {
  assert.strictEqual(BGC_PRICE_DISPLAY, pricing.display);
});

test('www/bgc-pricing.js is in sync with the generator (run `npm run generate:bgc-pricing`)', () => {
  assert.strictEqual(
    onDiskBrowser,
    expectedBrowser,
    'www/bgc-pricing.js drifted from lib/bgc-pricing.json — run `npm run generate:bgc-pricing` and commit the result.'
  );
});

test('www/bgc-pricing.js literal contains the canonical display value', () => {
  assert.ok(
    onDiskBrowser.includes(JSON.stringify(pricing.display)),
    `www/bgc-pricing.js should embed ${JSON.stringify(pricing.display)} but does not.`
  );
});

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
